### ISSUE TITLE
CDMI 2.X Spec - cdmi_encryption DSMD needs ref to TLS spec

### ISSUE THREAD

**Issue by dslik** [SNIA/CDMI-spec#170]
The text describing which encryption algorithms, modes and key lengths is out of date, and should point to the TLS spec (or the correct spec, if these are located elsewhere).

**Comment by dslik** [comment]
Ideally we'd point to the SNIA TLS Spec, section 6.2 (https://www.snia.org/sites/default/files/TLSspec-v1.01_Technical_Position.pdf), except this combines ciphers and hashing, and omits some algorithms that we want to support.

We ideally would point to another spec that defines these strings.

Deprecate 3DES_ECB_168

Similar changes need to be made for cdmi_value_hash

**Comment by dslik** [comment]
Mark: We should consult with Eric, invite to one of our meetings.

**Comment by macsun** [comment]
Eric not employed anymore.

**Comment by dslik** [comment]
We now refer to the latest TLS RFC and ISO 20648.

A separate issue (#264) to update the examples.
