### ISSUE TITLE
CDMI 2.0 Spec - Remove syntax highlighting from code examples

### ISSUE THREAD

**Issue by dslik** [SNIA/CDMI-spec#181]
The sphinx lexer has problems with many of our examples, so we should remove syntax highlighting from code/json/http examples.

This is done by using "none".

**Comment by dslik** [comment]
This requires a pass through the entire document, should do together with other tickets that require a similar full pass.

**Comment by pvliesdonk** [comment]
Run in linux-like:
`find ./ -type f -print0 | xargs -0 sed -i 's/code-block:: .*/code-block::/g'`

This replaces every line with a `.. code-block:: http` or `.. code-block:: json` to `.. code-block::`

**Comment by pvliesdonk** [comment]
Advice: commit, then run command, then check the diff.

**Comment by dslik** [comment]
".. code-block::" doesn't seem to work (the code cite no longer displays)

**Comment by dslik** [comment]
Fixed.
