### ISSUE TITLE
CDMI 2.0 Spec - Table of Tables should have "Table N" in first column

### ISSUE THREAD

**Issue by dslik** [SNIA/CDMI-spec#192]
In the table of tables, the first column says "1, 2, 3...", rather than "Table 1, Table 2, Table 3..."

**Comment by pvliesdonk** [comment]
Table of Tables layout can be overridden with [titletoc](http://ftp.snt.utwente.nl/pub/software/tex/macros/latex/contrib/titlesec/titlesec.pdf) package. Also works for #189 

Interesting post on [stackexchange](https://tex.stackexchange.com/questions/261364/modifying-list-of-tables-images)

**Comment by dslik** [comment]
Fixed.
