### ISSUE TITLE
CDMI 2.0 Spec - Cloud Service Provider

### ISSUE THREAD

**Issue by dslik** [SNIA/CDMI-spec#199]
Make sure we are using the correct ISO definition for Cloud Service Provider, and include the correct reference.

**Comment by dslik** [comment]
Mark: In ISO 17788?

**Comment by pvliesdonk** [comment]
From 17788:

> 3.2.15 cloud service provider: Party (3.1.6) which makes cloud services (3.2.8) available. 

> The following term is defined in ISO/IEC 27729:
> 3.1.6 party: Natural person or legal person, whether or not incorporated, or a group of either. 

> 3.2.8 cloud service: One or more capabilities offered via cloud computing (3.2.5) invoked using a defined interface. 

> 3.2.5 cloud computing: Paradigm for enabling network access to a scalable and elastic pool of shareable physical or virtual resources with self-service provisioning and administration on-demand.

**Comment by dslik** [comment]
Added "cloud service", as defined in the SNIA dictionary.

"cloud service provider" is no longer used in the spec.
