### ISSUE TITLE
CDMI 2.0 Spec - Example handling

### ISSUE THREAD

**Issue by sbs-jms** [SNIA/CDMI-spec#232]
- Examples are sometimes set apart with a text box (see 9.2.9) and sometimes are included in the text without a bounding box, but with block quote indentation (see 9.1.2). Is this intentional?

- Examples appear to be manually numbered with a restart for each identified clause. Would unified numbering (like tables or figures) be helpful? Looking at the ISO directives, this appears to be their preferred approach, as they require that the spec not rely on any content in the examples. Need to check that that is so.

- paired request / response examples, are handled similarly to boxed examples, but are not numbered, and include "the following" without specifying a limit (e.g., "the following three values") or a code snippet id (e.g., "as shown in example 4b")

**Comment by dslik** [comment]
Here's what the examples would look like if we use the "over the wire direction indication" style that I've seen used elsewhere:

[examples.pdf](https://github.com/SNIA/CDMI-spec/files/4357933/examples.pdf)

**Comment by sbs-jms** [comment]
Thanks, David. That could certainly work, particularly if there is a preamble somewhere that spells out the notation (in my experience "it's obvious" is not a favorite phrase of your average ISO editor). We can talk about it this afternoon.

**Comment by dslik** [comment]
Decision to use:

-->

<--

With a blank line between directions.

**Comment by dslik** [comment]
Also add text to clause 4.2 describing this syntax.

**Comment by dslik** [comment]
Determined that restarting example numbering is acceptable according to ISO directives.

All open issues resolved.
