### ISSUE TITLE
Figure references need consistent peramble

### ISSUE THREAD

**Issue by sbs-jms** [SNIA/CDMI-spec#238]
While the sphinx is consistent between the figure name and the reference, the  rendered PDF is not. While the text reference says 'fig 1', the caption on the referenced diagram says 'Figure 1'

See 5.1.3 for an example

**Comment by dslik** [comment]
Table of figures updated to use "Fig." instead of "Figure". Would prefer to use "Figure" consistently, but unable to quickly identify a way to fix this in the actual figure captions.
