### ISSUE TITLE
CDMI 2.0 Spec - Add abstract to title page

### ISSUE THREAD

**Issue by dslik** [SNIA/CDMI-spec#38]
The abstract needs to be added to the cover page.

ABSTRACT: This CDMI International Standard is intended for application developers who are implementing or using cloud storage. It documents how to access cloud storage and to manage the data stored there.

This document has been released and approved by the SNIA. The SNIA believes that the ideas, methodologies, and technologies described in this document accurately represent the SNIA goals and are appropriate for widespread distribution. Suggestion for revision should be directed to   http://www.snia.org/feedback/.

**Comment by dslik** [comment]
Assistance needed on how to add this text to the cover page.

**Comment by pvliesdonk** [comment]
Spinx titlepage can be overridden using the `maketitle` keyword in `latex_elements` inside `conf.py`.

This requires manually recreating the titlepage from scratch.

**Comment by dslik** [comment]
Titlepage updated to match SNIA conventions.
