### ISSUE TITLE
CDMI 2.0 Spec - Literals use quotes

### ISSUE THREAD

**Issue by dslik** [SNIA/CDMI-spec#85]
Decision to have exact literals (e.g. Field nnn shall have value "true"), where both nnn and true are in a monospaced font.

Also add to the conventions section of the document.

**Comment by sbs-jms** [comment]
How should be handle REST verbs? Current spec uses PUT and GET. Would ``put`` and ``get`` be an improvement?

**Comment by sbs-jms** [comment]
From 5.4.3:
We use '"Authorization" header' and 'Authorization header', as well as 'WWW-Authenticate` 

Should some/all of these be handled as fixed-space literals?
Is Authorization header a term of art?

**Comment by dslik** [comment]
All aspects of this issue have been resolved.
